"""empty message

Revision ID: fc58533c2862
Revises: 4f0a87141d0b
Create Date: 2018-11-04 17:51:38.205790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc58533c2862'
down_revision = '4f0a87141d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('school', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.create_unique_constraint(None, 'school', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school', type_='unique')
    op.alter_column('school', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_column('school', 'id')
    # ### end Alembic commands ###
